### ISSUE TITLE
Experimental API?

### ISSUE THREAD

**Issue by bderstine** [philamuseum/hackathon#1]
Was looking for the experimental API and didn't find the end point in the documentation. Can anyone point us in the direction?

**Comment by peteralt** [comment]
Hey Brad,

The API is located at https://hackathon.philamuseum.org
The documentation (after registering) is available at https://hackathon.philamuseum.org/documentation

If you go to the API Explorer https://hackathon.philamuseum.org/explorer you'll see the sample query constructed with your API key, so you can directly copy & paste that if needed.

Let me know if that helps or if there are other questions we can answer :)
